version: '3'

services:
  api-solid-pg:
    image: 'bitnami/postgresql'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRESQL_DATABASE: 'api-solid'
    container_name: 'api-solid-pg'